services:

  streamlit:
    build: .
    container_name: ai_ecommerce_streamlit

    ports:
      - "8501:8501"

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - ollama

    command: streamlit run streamlit_app/home.py --server.port=8501 --server.address=0.0.0.0

  fastapi:
    build: .
    container_name: ai_ecommerce_fastapi

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - ollama

    command: uvicorn api.app:app --host 0.0.0.0 --port 8000

  ollama:
    image: ollama/ollama

    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama

volumes:
  ollama: